# Generated by Django 4.2.11 on 2024-04-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boxmodel",
            options={
                "verbose_name": "Модель коробки",
                "verbose_name_plural": "Модели коробок",
            },
        ),
    ]
