# Generated by Django 5.0.2 on 2024-03-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_remove_productionorder_box_order_detail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionorder",
            name="box_order_detail",
        ),
        migrations.AddField(
            model_name="productionorder",
            name="box_order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_orders",
                to="production.boxorderdetail",
            ),
        ),
    ]
