# Generated by Django 5.0.2 on 2024-03-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_director",
            field=models.BooleanField(default=False),
        ),
    ]
